### PR TITLE
CE-15117 Update vault to 1.8.2

### PR DESCRIPTION
**Pull request by pkazi**
https://coupadev.atlassian.net/browse/CE-15117

### CODE REVIEW

**Review by Ramesh7 — APPROVED** [review]
lgtm

**Review by marutinandanpandya — APPROVED** [review]

**Comment by pkazi** [comment]
run tests

**Comment by pkazi** [comment]
rerun tests

**Comment by coupaopsin** [comment]
:rotating_light: PR Pipeline is in FAILED state - [[#Build-1](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/1/), [#Reports-1](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/1//Build_Reports)]

**Comment by coupaopsin** [comment]
:rotating_light: PR Pipeline is in FAILED state - [[#Build-2](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/2/), [#Reports-2](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/2//Build_Reports)]

**Comment by coupaopsin** [comment]
:rotating_light: PR Pipeline is in FAILED state - [[#Build-3](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/3/), [#Reports-3](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/3//Build_Reports)]

**Comment by coupaopsin** [comment]
:white_check_mark: PR Pipeline completed successfully - [[#Build-4](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/4/), [#Reports-4](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/4//Build_Reports)]

**Comment by coupaopsin** [comment]
:white_check_mark: PR Pipeline completed successfully - [[#Build-5](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/5/), [#Reports-5](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/5//Build_Reports)]

**Comment by coupaopsin** [comment]
:rotating_light: PR Pipeline is in FAILED state - [[#Build-9](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/9/), [#Reports-9](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/9//Build_Reports)]

**Comment by coupaopsin** [comment]
:white_check_mark: PR Pipeline completed successfully - [[#Build-10](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/10/), [#Reports-10](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/10//Build_Reports)]

**Comment by coupaopsin** [comment]
:white_check_mark: PR Pipeline completed successfully - [[#Build-11](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/11/), [#Reports-11](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/11//Build_Reports)]

**Comment by coupaopsin** [comment]
:white_check_mark: PR Pipeline completed successfully - [[#Build-12](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/12/), [#Reports-12](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/12//Build_Reports)]

**Comment by coupaopsin** [comment]
:white_check_mark: PR Pipeline completed successfully - [[#Build-13](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/13/), [#Reports-13](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/13//Build_Reports)]

**Pull request merged**
