### PR TITLE
CE-15118 branch and color fixes

### PR DESCRIPTION
**Pull request by pkazi**

### CODE REVIEW

**Comment by coupaopsin** [comment]
:rotating_light: PR Pipeline is in FAILED state - [[#Build-24](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/24/)]

**Comment by pkazi** [comment]
rerun tests

**Comment by coupaopsin** [comment]
:white_check_mark: PR Pipeline completed successfully - [[#Build-25](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/25/)]

**Comment by coupaopsin** [comment]
:white_check_mark: PR Pipeline completed successfully - [[#Build-26](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/26/)]

**Pull request merged**
