### PR TITLE
CE-19594 added vault 1.12.2

### PR DESCRIPTION
**Pull request by ssethi19**
##JIRA

[JIRA](https://coupadev.atlassian.net/browse/CE-19594)

## Summary

- Updating vault binary version to update the [go](https://github.com/hashicorp/vault/releases/tag/v1.12.2) library version

### CODE REVIEW

**Comment by coupaopsin** [comment]
:rotating_light: CI Pipeline is in FAILED state - [[#Build-38](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/38/)]

**Comment by ssethi19** [comment]
rerun test

**Comment by ssethi19** [comment]
rerun tests

**Comment by coupaopsin** [comment]
:rotating_light: CI Pipeline is in FAILED state - [[#Build-39](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/39/)]

**Comment by coupaopsin** [comment]
:rotating_light: CI Pipeline is in FAILED state - [[#Build-40](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/40/)]

**Comment by coupaopsin** [comment]
:rotating_light: CI Pipeline is in FAILED state - [[#Build-41](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/41/)]

**Comment by coupaopsin** [comment]
:rotating_light: CI Pipeline is in FAILED state - [[#Build-44](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/44/)]

**Comment by ssethi19** [comment]
rerun tests

**Comment by coupaopsin** [comment]
:rotating_light: CI Pipeline is in FAILED state - [[#Build-45](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/45/)]

**Comment by coupaopsin** [comment]
:white_check_mark: CI Pipeline completed successfully - [[#Build-46](https://jenkins-opstest.coupadev.com/job/Cloud_Engineering/job/docker-vault-ci-pipeline/46/)]

**Review by pkazi — APPROVED** [review]

**Review by KratiBansal — APPROVED** [review]

**Pull request merged**
